#include "../headers/teb_peb_offsets.hpp"
#include <unordered_map>
#include <cstdint>

std::unordered_map<uint64_t, const char*> gs_teb_offset_names = {
    {0x0,                                      "TEB (self-pointer)"}, 
    {TEB_OFFSET_StackBase,                     "TEB.StackBase"},
    {TEB_OFFSET_StackLimit,                    "TEB.StackLimit"},
    {TEB_OFFSET_SubSystemTib,                  "TEB.SubSystemTib"},
    {TEB_OFFSET_FiberData,                     "TEB.FiberData"},
    {TEB_OFFSET_ArbitraryDataSlot,             "TEB.ArbitraryDataSlot"},
    {TEB_OFFSET_SELF,                          "TEB (self-pointer duplicate)"},
    {TEB_OFFSET_EnvironmentPointer,            "TEB.EnvironmentPointer"},
    {TEB_OFFSET_ClientId_UniqueProcess,        "TEB.ClientID.Process"},
    {TEB_OFFSET_ClientId_UniqueThread,         "TEB.ClientID.Thread"},
    {TEB_OFFSET_ActiveRpcHandle,               "TEB.ActiveRPCHandle"},
    {TEB_OFFSET_TLSArray,                      "TEB.TLSArray"},
    {TEB_OFFSET_PEB,                           "TEB.PEB"},
    {TEB_OFFSET_LastErrorValue,                "TEB.LastErrorValue"},
    {TEB_OFFSET_CountOfOwnedCriticalSections,  "TEB.CountOfOwnedCriticalSections"},
    {TEB_OFFSET_CsrClientThread,               "TEB.CsrClientThread"},
    {TEB_OFFSET_Win32ThreadInfo,               "TEB.Win32ThreadInfo"},
    {TEB_OFFSET_Win32ClientInfo,               "TEB.Win32ClientInfo"},
    {TEB_OFFSET_Wow64Reserved,                 "TEB.Wow64Reserved"},
    {TEB_OFFSET_CurrentLocale,                 "TEB.CurrentLocale"},
    {TEB_OFFSET_FPSoftwareStatusRegister,      "TEB.FPSoftwareStatusRegister"},
    {TEB_OFFSET_DeallocationStack,             "TEB.DeallocationStack"},
    {TEB_OFFSET_TLS_Slots,                     "TEB.TLS_Slots"},
    {TEB_OFFSET_TLS_Links,                     "TEB.TLS_Links"},
    {TEB_OFFSET_GuaranteedStackBytes,          "TEB.GuaranteedStackBytes"},
};


std::unordered_map<uint64_t, const char*> gs_peb_offset_names = {
    {PEB_OFFSET_InheritedAddressSpace,         "PEB.InheritedAddressSpace"},
    {PEB_OFFSET_ReadImageFileExecOptions,      "PEB.ReadImageFileExecOptions"},
    {PEB_OFFSET_BeingDebugged,                 "PEB.BeingDebugged"},
    {PEB_OFFSET_BitField,                      "PEB.BitField"},
    {PEB_OFFSET_Mutant,                        "PEB.Mutant"},
    {PEB_OFFSET_ImageBaseAddress,              "PEB.ImageBaseAddress"},
    {PEB_OFFSET_Ldr,                           "PEB.Ldr"},
    {PEB_OFFSET_ProcessParameters,             "PEB.ProcessParameters"},
    {PEB_OFFSET_SubSystemData,                 "PEB.SubSystemData"},
    {PEB_OFFSET_ProcessHeap,                   "PEB.ProcessHeap"},
    {PEB_OFFSET_FastPebLock,                   "PEB.FastPebLock"},
    {PEB_OFFSET_AtlThunkSListPtr,              "PEB.AtlThunkSListPtr"},
    {PEB_OFFSET_IFEOKey,                       "PEB.IFEOKey"},
    {PEB_OFFSET_CrossProcessFlags,             "PEB.CrossProcessFlags"},
    {PEB_OFFSET_KernelCallbackTable,           "PEB.KernelCallbackTable"},
    {PEB_OFFSET_SystemReserved,                "PEB.SystemReserved"},
    {PEB_OFFSET_AtlThunkSListPtr32,            "PEB.AtlThunkSListPtr32"},
    {PEB_OFFSET_ApiSetMap,                     "PEB.ApiSetMap"},
    {PEB_OFFSET_TlsExpansionCounter,           "PEB.TlsExpansionCounter"},
    {PEB_OFFSET_TlsBitmap,                     "PEB.TlsBitmap"},
    {PEB_OFFSET_TlsBitmapBits,                 "PEB.TlsBitmapBits"},
    {PEB_OFFSET_ReadOnlySharedMemoryBase,      "PEB.ReadOnlySharedMemoryBase"},
    {PEB_OFFSET_SharedData,                    "PEB.SharedData"},
    {PEB_OFFSET_ReadOnlyStaticServerData,      "PEB.ReadOnlyStaticServerData"},
    {PEB_OFFSET_AnsiCodePageData,              "PEB.AnsiCodePageData"},
    {PEB_OFFSET_OemCodePageData,               "PEB.OemCodePageData"},
    {PEB_OFFSET_UnicodeCaseTableData,          "PEB.UnicodeCaseTableData"},
    {PEB_OFFSET_NumberOfProcessors,            "PEB.NumberOfProcessors"},
    {PEB_OFFSET_NtGlobalFlag,                  "PEB.NtGlobalFlag"},
    {PEB_OFFSET_CriticalSectionTimeout,        "PEB.CriticalSectionTimeout"},
    {PEB_OFFSET_HeapSegmentReserve,            "PEB.HeapSegmentReserve"},
    {PEB_OFFSET_HeapSegmentCommit,             "PEB.HeapSegmentCommit"},
    {PEB_OFFSET_HeapDeCommitTotalFreeThreshold,"PEB.HeapDeCommitTotalFreeThreshold"},
    {PEB_OFFSET_HeapDeCommitFreeBlockThreshold,"PEB.HeapDeCommitFreeBlockThreshold"},
    {PEB_OFFSET_NumberOfHeaps,                 "PEB.NumberOfHeaps"},
    {PEB_OFFSET_MaximumNumberOfHeaps,          "PEB.MaximumNumberOfHeaps"},
    {PEB_OFFSET_ProcessHeaps,                  "PEB.ProcessHeaps"},
    {PEB_OFFSET_GdiSharedHandleTable,          "PEB.GdiSharedHandleTable"},
    {PEB_OFFSET_ProcessStarterHelper,          "PEB.ProcessStarterHelper"},
    {PEB_OFFSET_GdiDCAttributeList,            "PEB.GdiDCAttributeList"},
    {PEB_OFFSET_LoaderLock,                    "PEB.LoaderLock"},
    {PEB_OFFSET_OSMajorVersion,                "PEB.OSMajorVersion"},
    {PEB_OFFSET_OSMinorVersion,                "PEB.OSMinorVersion"},
    {PEB_OFFSET_OSBuildNumber,                 "PEB.OSBuildNumber"},
    {PEB_OFFSET_OSCSDVersion,                  "PEB.OSCSDVersion"},
    {PEB_OFFSET_OSPlatformId,                  "PEB.OSPlatformId"},
    {PEB_OFFSET_ImageSubsystem,                "PEB.ImageSubsystem"},
    {PEB_OFFSET_ImageSubsystemMajorVersion,    "PEB.ImageSubsystemMajorVersion"},
    {PEB_OFFSET_ImageSubsystemMinorVersion,    "PEB.ImageSubsystemMinorVersion"},
    {PEB_OFFSET_ActiveProcessAffinityMask,     "PEB.ActiveProcessAffinityMask"},
    {PEB_OFFSET_GdiHandleBuffer,               "PEB.GdiHandleBuffer"},
    {PEB_OFFSET_PostProcessInitRoutine,        "PEB.PostProcessInitRoutine"},
    {PEB_OFFSET_TlsExpansionBitmap,            "PEB.TlsExpansionBitmap"},
    {PEB_OFFSET_TlsExpansionBitmapBits,        "PEB.TlsExpansionBitmapBits"},
    {PEB_OFFSET_SessionId,                     "PEB.SessionId"},
    {PEB_OFFSET_AppCompatFlags,                "PEB.AppCompatFlags"},
    {PEB_OFFSET_AppCompatFlagsUser,            "PEB.AppCompatFlagsUser"},
    {PEB_OFFSET_pShimData,                     "PEB.pShimData"},
    {PEB_OFFSET_AppCompatInfo,                 "PEB.AppCompatInfo"},
    {PEB_OFFSET_CSDVersion,                    "PEB.CSDVersion"},
    {PEB_OFFSET_ActivationContextData,         "PEB.ActivationContextData"},
    {PEB_OFFSET_ProcessAssemblyStorageMap,     "PEB.ProcessAssemblyStorageMap"},
    {PEB_OFFSET_SystemDefaultActivationContextData, "PEB.SystemDefaultActivationContextData"},
    {PEB_OFFSET_SystemAssemblyStorageMap,      "PEB.SystemAssemblyStorageMap"},
    {PEB_OFFSET_MinimumStackCommit,            "PEB.MinimumStackCommit"},
};

